import { CommonHeader } from "@/components/organisms/common/CommonHeader";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CommonHeader />
        <main className="max-w-2xl mx-auto p-4 rounded-2xl shadow-md pt-6 bg-gradient-to-br from-white via-blue-50 to-blue-100 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
